# permissions to do viewer clusteraddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusteraddon-viewer-role
rules:
- apiGroups:
  - clusterops.mmlt.nl
  resources:
  - clusteraddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterops.mmlt.nl
  resources:
  - clusteraddons/status
  verbs:
  - get
